services:
  - type: web
    name: boardapp
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p templates
      cp -r templates/* templates/
      python wsgi.py
    startCommand: gunicorn boardapp:app
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: boardapp-db
          property: connectionString
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - templates/**/*

databases:
  - name: boardapp-db
    databaseName: boardapp
    user: boardapp
    plan: free
