services:
  - type: web
    name: boardapp
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance
    startCommand: |
      cd /opt/render/project/src && \
      PYTHONPATH=/opt/render/project/src \
      gunicorn \
        --bind=0.0.0.0:$PORT \
        --workers=2 \
        --threads=4 \
        --worker-class=gthread \
        --worker-tmp-dir=/dev/shm \
        --log-level=debug \
        boardapp:app
    envVars:
      - key: FLASK_APP
        value: boardapp
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: boardapp-db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "false"
      - key: SQLALCHEMY_ENGINE_OPTIONS
        value: '{"pool_size": 10, "max_overflow": 20, "pool_timeout": 30, "pool_recycle": 1800, "pool_pre_ping": true}'

databases:
  - name: boardapp-db
    databaseName: boardapp
    user: boardapp
    plan: free
