services:
  - type: web
    name: boardapp
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance
      ls -la
      pwd
      PYTHONPATH=$PWD python -c "from boardapp import app, db; app.app_context().push(); db.create_all()"
    startCommand: gunicorn "boardapp:app" --bind 0.0.0.0:$PORT --log-level debug --timeout 120 --workers 4 --threads 2 --chdir /opt/render/project/src
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: boardapp-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: GUNICORN_CMD_ARGS
        value: "--access-logfile - --error-logfile -"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - templates/**/*

databases:
  - name: boardapp-db
    databaseName: boardapp
    user: boardapp
    plan: free
