services:
  - type: web
    name: boardapp
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance
      echo "Starting database initialization..."
      PYTHONPATH=$PWD python -c "
      import sys
      from boardapp import app, db
      from sqlalchemy import text
      with app.app_context():
          print('Testing database connection...')
          try:
              db.engine.connect().execute(text('SELECT 1'))
              print('Database connection successful')
              print('Creating database tables...')
              db.create_all()
              print('Database tables created successfully')
          except Exception as e:
              print(f'Database initialization error: {e}', file=sys.stderr)
              print(f'Python path: {sys.path}', file=sys.stderr)
              print(f'Current working directory: {sys.getcwd()}', file=sys.stderr)
              raise
      "
    startCommand: cd /opt/render/project/src && PYTHONPATH=/opt/render/project/src gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --worker-class=gthread --worker-tmp-dir=/dev/shm --preload --max-requests 1000 --max-requests-jitter 50 --log-level info
    healthCheckPath: /health
    healthCheckTimeout: 5
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: boardapp
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: boardapp-db
          property: connectionString
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "false"
      - key: SQLALCHEMY_ENGINE_OPTIONS
        value: '{"pool_size": 10, "max_overflow": 20, "pool_timeout": 30, "pool_recycle": 1800, "pool_pre_ping": true}'
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SESSION_COOKIE_HTTPONLY
        value: "true"
      - key: SESSION_COOKIE_SAMESITE
        value: "Lax"
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - templates/**/*

databases:
  - name: boardapp-db
    databaseName: boardapp
    user: boardapp
    plan: free
